# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # NOTE: these UUID-based mounts override disko-config.nix's generated
  # by-partlabel mounts via lib.mkForce, so the system can be rebuilt on the
  # currently-installed disk (which was not partitioned via disko).
  # On a fresh disko-driven install, drop the mkForce wrappers (or remove
  # this block entirely) and rely on disko's own fileSystems definitions.
  fileSystems."/" = lib.mkForce {
    device = "/dev/disk/by-uuid/ccac5ac8-67a6-4eb2-86c4-6ff5824eab93";
    fsType = "btrfs";
  };

  fileSystems."/boot" = lib.mkForce {
    device = "/dev/disk/by-uuid/3E40-8F7D";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  # Enable DHCP fallback (networkmanager handles wifi)
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
